![](http://research.ncsu.edu/dsi/files/2014/10/data-science2.jpg)

# Linear Algebra

> If people do not believe that mathematics is simple, it is only because they do not realize how complicated life is

<footer>~ John von Neumann, 1947 ACM keynote</footer>

![break](assets/agenda.png)

1. Linear Algebra Review
1. The Python Control Flow

**Labs** :
1. Matrix Multiplication In Python
1. Adding Control Flow Into Clicks Aggregation

![break](assets/theory.png)

## Linear Algebra Review

In order to best understand most machine learning algorithms, we need some basis of linear algebra.

> Linear algebra is best defined as mathematics in the multidimensional space and the mapping between said spaces.

### For Example

$$y = mx + b$$

$$y = m_{1}x_{1} + m_{2}x_{2} + b$$

$$y = m_{1}x_{1} + m_{2}x_{2} + m_{3}x_{3} + m_{4}x_{4} + b$$

$$y = m_{1}x_{1} + m_{2}x_{2} + m_{3}x_{3} + m_{4}x_{4} + m_{5}x_{5} + m_{6}x_{6} + m_{7}x_{7} + m_{8}x_{8} + m_{9}x_{9} + m_{10}x_{10} + b$$

### Matrices

> Matrices are an array of real numbers with m rows and n columns

Each value in a matrix is called an entry.

$$\begin{bmatrix}1 & 5 & 8 & 7\\2 & 1 & 3 & 6\\3 & 5 & 1 & 0\\4 & 6 & 0 & 1\end{bmatrix}$$

$A_{21}$ in the given matrix, refers to the entry on the 2nd row, in the 1st column. The value is 2. 

### Vectors

> Vectors are a special kind of matrix, as they only consist of one dimension of real numbers.

These look most like a numeric array (or **list**) in Python.

$$\begin{bmatrix}1 & 3 & 9 & 2\end{bmatrix}$$

Likewise, you can refer to each index or value similarly (`a[0]` in Python is the same entity as 0 in vector a)

#### What can vectors capture?

In [ ]:
vec = [3.14159, 2.718281828, -1.0, 2.0]

Another example: $GF(2)^5$ is set of 5-element bit sequences, e.g. [0,0,0,0,0], and

In [ ]:
[0,0,0,0,1]

Let `WORDS` be the set of all English word

In information retrieval, a document is represented (“bag of words” model) by a
function

$$f : WORDS \rightarrow \mathbb{R}$$

specifying, for each word, how many times it appears in the document.

We often use Python’s dictionaries to represent such functions, e.g.

In [ ]:
{0:3.14159, 1:2.718281828, 2:-1.0, 3:2.0}

What about representing a WORDS-vector over $\mathbb{R}$?

For any single document, most words are not _represented_. They should be
mapped to zero.

Our convenient convention for representing vectors by dictionaries: allowed to
omit key-value pairs when value is zero.

**Example**

> The rain in Spain falls mainly on the plain” would be represented by
the dictionary

In [ ]:
{'on': 1, 'Spain': 1, 'in': 1, 'plain': 1, 'the': 2,
'mainly': 1, 'rain': 1, 'falls': 1}

* Document (for information retrieval)
* Binary string (for cryptography/information theory)
* Collection of attributes
    - LegCo voting record
    - Demographic record of a consumer
    - characteristics of cancer cells
* State of a system
    - Population distribution in the world
    - Number of copies of a virus in a computer network
    - state of a game of Sudoku

### Handling

**Rule 1!**

Matrices can be added together only when they are the same size. If they are not the same size, their sum is **undefined**.

$$\begin{bmatrix}1 & 3 & 9 & 2\end{bmatrix} + \begin{bmatrix}2 & 5 & 9 & 4\end{bmatrix} = 
\begin{bmatrix}3 & 8 & 18 & 6\end{bmatrix} $$



$$\begin{bmatrix}8 & 72 & 3 & 1\end{bmatrix} + \begin{bmatrix}17 & 55 & 3 & 10\end{bmatrix} = 
 \ ? $$

**Rule 2!**

Matrices can be multiplied by a scalar (single entity) value.

> Each value in the matrix is multiplied by the scalar value.


$$\begin{bmatrix}1 & 3 & 9 & 2\end{bmatrix} * 3 =
\begin{bmatrix}3 & 9 & 27 & 6\end{bmatrix} $$


$$\begin{bmatrix}8 & 72 & 3 & 1\end{bmatrix} * 2 = \ ? $$


**Rule 3!**

Matrices and vectors can be multiplied together given that the matrix columns are as wide as the vector is long. 

> The result will always be a vector.

$$\begin{bmatrix}1 & 3 & 9 & 2\\2 & 4 & 6 & 8\end{bmatrix} * \begin{bmatrix}2 \\ 3 \\ 6 \\ 5  \end{bmatrix} = \begin{matrix} 2 + 9 + 54 + 10 \\ 4 + 12 + 36 + 40 \end{matrix} = \begin{bmatrix} 75 \\ 92 \end{bmatrix}$$

**Rule 4!**

Matrices can be multiplied together using the same rules that we have from matrix-vector multiplication.

> The result will always be a matrix.

$$\begin{bmatrix}1 & 3 & 9 & 2\\2 & 4 & 6 & 8\end{bmatrix} * \begin{bmatrix}2 & 1 \\ 3 & 2 \\ 6 & 0 \\ 5 & 4 \end{bmatrix} = \begin{matrix} 2 + 9 + 54 + 10 \\ 4 + 12 + 36 + 40 \\ 1 + 6 + 0 + 8 \\ 2 + 8 + 0 + 32\end{matrix} = \begin{bmatrix} 75 & 15 \\ 92 & 42 \end{bmatrix}$$


### That Was Fast... Why Does This Matter?

Matrices represent the multiple dimensions in our data! If we had a vector that suggested how important each dimension of our data was, we could use that to find our best **linear model**.

**Rule 5!**

When vectors are multiplied _item-wise_ , that is, each item for one vector is multiplied with the item in the same _position_ in another vector, it is called the **dot-product** of the two vectors.

Suppose D consists of four main ingredients of beer:

```    
D = {barley, hops, yeast,water}
```

A cost vector maps each food to a price per unit amount:
```    
cost = {barley : $0.5, hops : $0.5, yeast : $.28/g,water : $0.05}
```
A quantity vector maps each food to an amount (e.g. measured in pounds).
```
quantity = {barley:0.5 lbs, hops:0.2 oz, yeast:2.5 g, water:10 gallons}
```
The total cost is the dot-product of cost with quantity:
```    
cost · quantity = $0.5 · 0.5 + $0.5 · 0.2 + $0.28 · 2.5 + $0.05 · 10 = $1.55
```
A value vector maps each food to its caloric content per pound:
```
value = {barley : 544, hops : 101, yeast : 83,water : 0}
```
The total calories represented by a pint of beer is the dot-product of value with
quantity:
```
value · quantity = 544 · 0.5 + 101 · 0.5 + 83 · 2.5+0 · 10 = 530
```

We will see matrices quite often in **all** of our data, so pay careful attention to how data is structured and how different algorithms interact with them.

![break](assets/code.png)

## Python Control Flow

### Control Flow

Python has a number of control flow tools that will be familiar from other languages. 

> The first is the if-else statement, whose compound syntax looks like this:

In [ ]:
x, y = False, True

In [ ]:
if x:
    print 'apollo'
elif y:
    print 'starbuck'
else:
    print 'adama'

Next is the while loop. 

> This executes while a given condition evaluates to True.


In [12]:
x = 0

In [7]:
while True:
    x += 1
    if x > 3:
        break
    print 'Galactica'

Galactica
Galactica
Galactica


In [13]:
while x < 3:
    x += 1
    print 'Galactica'

Galactica
Galactica
Galactica


Another familiar (and useful) construct is the for loop.

> This executes a block of code for a range of values.

In [19]:
range(2,20,2)

[2, 4, 6, 8, 10, 12, 14, 16, 18]

In [12]:
for k in range(4):
    print k**2

0
1
4
9


The object that a for loop iterates over is called
(appropriately) an iterable.

A useful but possibly unfamiliar construct is the try-
except block:

In [20]:
dict(zip(range(10),[x**2 for x in range(10)]))

9

In [21]:
print undef

NameError: name 'undef' is not defined

In [31]:
try:
    print undef
except NameError:
    print 'nice try, mr undefined!'        

nice try, mr undefined!


This is useful for catching and dealing with errors, also called exception handling.

### Functions

Python allows you to define custom functions as you
would expect:


In [23]:
def x_minus_3(x):
    return x - 3

In [ ]:
x_minus_3(12)

Functions can optionally return a value with a return statement (as this example does).

Functions can take a number of arguments as inputs,
and these arguments can be specified in two ways:


#### As positional arguments

In [37]:
def f(x=10,y=0):
    return x - y

In [29]:
import pandas as pd

In [ ]:
pd.read_csv()

In [38]:
f(y=10)

0

In [39]:
f(x=4,y=2)

2

In [42]:
f(y=2,x=4)

2

#### Or as keyword arguments

In [36]:
def g(arg1=1, arg2=1, arg3=1):
    return arg1 / float(arg2)

In [37]:
g(arg1=10, arg3=5)

10.0

In [38]:
g(arg2=100, arg1=10)

0.1

![break](assets/code.png)

## Lab: Matrix Addition In Python

* Build some basic linear algebra functions
* Improve comfort with flow patterns
* Explore list comprehensions

### Practice: Linear Algebra

Primarily let's focus on some of the concrete components we talked about in class

#### Matrices and Vectors

For the most part, we can consider using lists to create matrices and vectors (especially given that a Python list is, essentially, a vector)

In [39]:
vector = [1, 2, 3]
matrix = [ [1, 2, 3, 4], 
           [5, 6, 7, 8],
           [9, 0, 1, 2] ]

print matrix

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 0, 1, 2]]


In [42]:
matrix[1][0]

5

We'll learn more about `numpy` next week, but numpy makes it incredibly easy to auto generate both of these!

In [40]:
import numpy as np
npMatrix = np.matrix('1 2 3; 4 5 6; 7 8 9')

print npMatrix

[[1 2 3]
 [4 5 6]
 [7 8 9]]


#### Math

In [43]:
vector

[1, 2, 3]

In [48]:
vector * 3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

Note that "common sense" here won't work: we're looking for a way to multiply each value within a vector by a value, not to repeat the vector 3 times. Here, we can use _[list comprehensions](http://www.secnetix.de/olli/Python/list_comprehensions.hawk)_ instead:


In [57]:
items = ['1','2','3','4']

[int(item) for item in items]

[1, 2, 3, 4]

In [58]:
[x*3 for x in vector]

[3, 6, 9]

And easier, we can write this as a function.

In [51]:
def vectorScalarMultiply(vector, scalar):
    return [x*scalar for x in vector]

vectorScalarMultiply(vector, 3)

[3, 6, 9]

(Granted, we could extend the list class… but let's not and say we did)

Can also use list comprehensions to transpose a matrix, which should turn the matrix, essentially, on its 'diagonal axis'.


In [56]:
matrix

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 0, 1, 2]]

In [55]:
range(len(matrix[0]))

[0, 1, 2, 3]

In [53]:
[ [row[n] for row in matrix] for n in [0, 1, 2, 3]]

[[1, 5, 9], [2, 6, 0], [3, 7, 1], [4, 8, 2]]

In [60]:
import numpy as np

def matrixTranspose(matrix):
    """
    Matrix Transpose function with interspersed print statements
    for explanatory purposes. We'll disect the following list comprehension :
    
    [ [row[n] for row in matrix] for n in range(len(matrix[0]))]
    
    """
    
#   Let's inspect which  matrix was provided as an argument? : 
#
#    [[1 2 3 4]
#     [5 6 7 8]
#     [9 0 1 2]]
#
    print np.matrix(matrix)
    
#   Now, let's disect the list comprehension which will transpose this
#   matrix. Start from the back when trying to understand what a list 
#   comprehension does. So we see that it tries the access the first 
#   row in the Matrix : [1 2 3 4]
    print matrix[0]
    
#   It does this to determine the number of columns the matrix has, as
#   each row will have an equal number of elements. 
    print len(matrix[0])

#   The number of columns is them used to create a 'range list' to 
#   iterate over : [0, 1, 2, 3]
    print range(len(matrix[0]))

#   So in this particular case the list comprehension is simply:
#   [ INNERLOOP for n in [0,1,2,3]]

#   INNERLOOP : [row[n] for row in matrix]

#   The outer loop (the outer list comprehension) 'locks' the column
#   number for each full cycle of inner loop (inner list comprehension).

#   So in first instance 'n' is fixed at 0, and so when it executes the
#   inner loop :

#   [row[n] for row in matrix]

#  it goes through each row in the matrix and takes the nth element from the 
#  row. In the example, in the first cycle 'n' would be 0, and so the elements
#  taken from our examplary matrix would be [1,5,9]. These numbers are stored 
#  inside of a list (that's what list comprehensions do), and it will ask for 
#  the next value of 'n'. Now that 'n' is fixed as 1, it will go through a whole 
#  cycle again. Now it takes [2,6,0] from out examplary matrix. This continues 
#  for as long as there are more rows in the matrix.

    return [ [row[n] for row in matrix] for n in range(len(matrix[0]))]

#  Ultimately the function returns the transposed matrix : 
#
#   [[1 5 9]
#    [2 6 0]
#    [3 7 1]
#    [4 8 2]]
#
print np.matrix(matrixTranspose(matrix)) # Formatted as a matrix

[[1 2 3 4]
 [5 6 7 8]
 [9 0 1 2]]
[1, 2, 3, 4]
4
[0, 1, 2, 3]
[[1 5 9]
 [2 6 0]
 [3 7 1]
 [4 8 2]]


```python
[ [row[n] for row in matrix] for n in [0,1,2,3]]
```

### Classwork

1. Write two more functions: `vectorMatrix multiplication` and `matrix multiplication`. No numpy/scipy! Do this with pure python. Use triple quotes/doc quotes to explain the properties expected for a matrix in these functions:


In [ ]:
def vectorMatrixMultiplication(matrix,vector):
    """
    Explain exactly what is needed
    """
    return answer

Submit this code as a [Gist](http://gist.github.com) and submit it through the [homework submission](https://docs.google.com/a/type.hk/forms/d/1bc9B8_ZUhBFnNSjYtP_3ml2KoIOqTiW5yxkNhWQ9xBQ/viewform?c=0&w=1) form when you're done. Check your answers using the logic we went over from lecture.

**PROGRAMMER GOAL**

Write test cases and use try/catch in your functions for when matrices are not defined correctly (ie: [ [1,2,3], [4,5] ] is not a matrix.) Or, create a matrix class that also follows these rules.


2. Write a function that creates an identity matrix. An identity matrix is a matrix where value = 1 if the row and column index are the same, and 0 otherwise. It should build any size identity matrix you want.

Example: iMatrix(4) should be:

In [ ]:
[[1, 0, 0, 0],
[0, 1, 0, 0],
[0, 0, 1, 0],
[0, 0, 0, 1] ]

**Send it your scripts as a Gist!**

## Mini Project

Let's revise the original script we wrote on Class01 to now return a new csv file that summarizes the data in such a way:

```
# HEADERS:

"age", "gender", "signed_in", "avg_click", "avg_impressions", "max_click", "max_impressions"
```

This means that we are now aggregating data by age, gender, and signed_in to get these new data features: avg_click, avg_impressions, max_click, max_impressions.
Let's include Age = 0 (null age) as a possible groupable.

![break](assets/resources.png)

## Resources

#### Mathematics
* [Great review on Linear Algebra](http://cs229.stanford.edu/section/cs229-linalg.pdf)
* [Coding the Matrix: Linear Algebra through Computer Science Applications](https://www.coursera.org/course/matrix) - Learn the concepts and methods of linear algebra, and how to use them to think about computational problems arising in computer science. Coursework includes building on the concepts to write small programs and run them on real data.

#### Machine Learning
[Early learning on its application to linear models](http://dept.stat.lsa.umich.edu/~kshedden/Courses/Stat401/Notes/401-multreg.pdf)

#### Code
[A Matrix Class implemented in pure python](http://code.activestate.com/recipes/189971-basic-linear-algebra-matrix/)

## Colofon

In [4]:
from utils import *
print_versions()

Python    2.7.10
IPython   4.0.0
numpy     1.10.1
pandas    0.17.0
sklearn   0.17
seaborn   0.6.0


In [5]:
%%html

<link rel="stylesheet" href="theme/custom.css">